from typing import Dict, Any, Optional
from datetime import datetime, timezone
import uuid
from app.services.collectors.envelope import ObservationEnvelope

class ObservationBuilder:
    """
    Enforces a strict schema for observations generated by collectors.
    Collectors must use this builder instead of creating raw dictionaries.
    """
    def __init__(self, tenant_id: str, collector_id: str, collection_job_id: Optional[str] = None):
        self.tenant_id = tenant_id
        self.collector_id = collector_id
        self.collection_job_id = collection_job_id
        self.payload: Dict[str, Any] = {}
        self.evidence: Dict[str, Any] = {
            "sources": [],
            "trust": 0.0,
            "timestamp": datetime.now(timezone.utc).isoformat()
        }
        self.resource_hint: Optional[str] = None
        
    def with_fact(self, key: str, value: Any, trust: float = 0.5, source_hint: str = None) -> 'ObservationBuilder':
        """Adds a fact to the payload and records evidence."""
        self.payload[key] = value
        self.evidence["trust"] = max(self.evidence["trust"], trust)
        if source_hint and source_hint not in self.evidence["sources"]:
            self.evidence["sources"].append(source_hint)
        return self
        
    def with_resource_hint(self, hint: str) -> 'ObservationBuilder':
        """Provides a hint for the identity resolution engine."""
        self.resource_hint = hint
        return self
        
    def build(self, priority: int = 100) -> ObservationEnvelope:
        """Constructs the final ObservationEnvelope."""
        return ObservationEnvelope(
            id=uuid.uuid4(),
            tenant_id=self.tenant_id,
            collector_id=self.collector_id,
            collection_job_id=self.collection_job_id,
            priority=priority,
            payload=self.payload,
            evidence=self.evidence
        )
