"""Add topology models

Revision ID: 0003baaecde7
Revises: ad5efdc3c9be
Create Date: 2026-07-27 11:48:03.746235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003baaecde7'
down_revision: Union[str, Sequence[str], None] = 'ad5efdc3c9be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topology_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stream_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.Column('causation_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_events_actor_id'), 'topology_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_topology_events_causation_id'), 'topology_events', ['causation_id'], unique=False)
    op.create_index(op.f('ix_topology_events_correlation_id'), 'topology_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_topology_events_event_type'), 'topology_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_topology_events_stream_id'), 'topology_events', ['stream_id'], unique=False)
    op.create_index('ix_topology_events_stream_version', 'topology_events', ['stream_id', 'version'], unique=True)
    op.create_table('topology_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('collector_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_observations_collector_id'), 'topology_observations', ['collector_id'], unique=False)
    op.create_index(op.f('ix_topology_observations_observed_at'), 'topology_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_topology_observations_protocol'), 'topology_observations', ['protocol'], unique=False)
    op.create_index(op.f('ix_topology_observations_site_id'), 'topology_observations', ['site_id'], unique=False)
    op.create_table('topology_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('graph_type', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot_hash', sa.String(), nullable=True),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('edge_count', sa.Integer(), nullable=False),
    sa.Column('finding_count', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_snapshots_graph_type'), 'topology_snapshots', ['graph_type'], unique=False)
    op.create_index(op.f('ix_topology_snapshots_site_id'), 'topology_snapshots', ['site_id'], unique=False)
    op.create_index('ix_topology_snapshots_site_version', 'topology_snapshots', ['site_id', 'version'], unique=True)
    op.create_index(op.f('ix_topology_snapshots_tenant_id'), 'topology_snapshots', ['tenant_id'], unique=False)
    op.create_table('topology_ai_contexts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('embedding_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['topology_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_ai_contexts_snapshot_id'), 'topology_ai_contexts', ['snapshot_id'], unique=False)
    op.create_table('topology_layouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('layout_name', sa.String(), nullable=False),
    sa.Column('algorithm', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['topology_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_layouts_layout_name'), 'topology_layouts', ['layout_name'], unique=False)
    op.create_index(op.f('ix_topology_layouts_snapshot_id'), 'topology_layouts', ['snapshot_id'], unique=False)
    op.create_table('topology_simulations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['topology_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_simulations_snapshot_id'), 'topology_simulations', ['snapshot_id'], unique=False)
    op.create_table('topology_validation_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('critical', sa.Integer(), nullable=False),
    sa.Column('warning', sa.Integer(), nullable=False),
    sa.Column('info', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['topology_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topology_validation_reports_snapshot_id'), 'topology_validation_reports', ['snapshot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topology_validation_reports_snapshot_id'), table_name='topology_validation_reports')
    op.drop_table('topology_validation_reports')
    op.drop_index(op.f('ix_topology_simulations_snapshot_id'), table_name='topology_simulations')
    op.drop_table('topology_simulations')
    op.drop_index(op.f('ix_topology_layouts_snapshot_id'), table_name='topology_layouts')
    op.drop_index(op.f('ix_topology_layouts_layout_name'), table_name='topology_layouts')
    op.drop_table('topology_layouts')
    op.drop_index(op.f('ix_topology_ai_contexts_snapshot_id'), table_name='topology_ai_contexts')
    op.drop_table('topology_ai_contexts')
    op.drop_index(op.f('ix_topology_snapshots_tenant_id'), table_name='topology_snapshots')
    op.drop_index('ix_topology_snapshots_site_version', table_name='topology_snapshots')
    op.drop_index(op.f('ix_topology_snapshots_site_id'), table_name='topology_snapshots')
    op.drop_index(op.f('ix_topology_snapshots_graph_type'), table_name='topology_snapshots')
    op.drop_table('topology_snapshots')
    op.drop_index(op.f('ix_topology_observations_site_id'), table_name='topology_observations')
    op.drop_index(op.f('ix_topology_observations_protocol'), table_name='topology_observations')
    op.drop_index(op.f('ix_topology_observations_observed_at'), table_name='topology_observations')
    op.drop_index(op.f('ix_topology_observations_collector_id'), table_name='topology_observations')
    op.drop_table('topology_observations')
    op.drop_index('ix_topology_events_stream_version', table_name='topology_events')
    op.drop_index(op.f('ix_topology_events_stream_id'), table_name='topology_events')
    op.drop_index(op.f('ix_topology_events_event_type'), table_name='topology_events')
    op.drop_index(op.f('ix_topology_events_correlation_id'), table_name='topology_events')
    op.drop_index(op.f('ix_topology_events_causation_id'), table_name='topology_events')
    op.drop_index(op.f('ix_topology_events_actor_id'), table_name='topology_events')
    op.drop_table('topology_events')
    # ### end Alembic commands ###
