"""Add policy and finding models

Revision ID: 15ad077c1d98
Revises: 65680ea45859
Create Date: 2026-08-04 18:32:45.722025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15ad077c1d98'
down_revision: Union[str, Sequence[str], None] = '65680ea45859'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_name'), 'policies', ['name'], unique=False)
    op.create_index(op.f('ix_policies_tenant_id'), 'policies', ['tenant_id'], unique=False)
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('origin_engine', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_findings_origin_engine'), 'findings', ['origin_engine'], unique=False)
    op.create_index(op.f('ix_findings_resource_id'), 'findings', ['resource_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_index(op.f('ix_findings_tenant_id'), 'findings', ['tenant_id'], unique=False)
    op.create_table('policy_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_assignments_policy_id'), 'policy_assignments', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_assignments_resource_id'), 'policy_assignments', ['resource_id'], unique=False)
    op.create_table('policy_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('match_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rule_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_versions_policy_id'), 'policy_versions', ['policy_id'], unique=False)
    op.create_table('finding_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_states_finding_id'), 'finding_states', ['finding_id'], unique=False)
    op.create_index(op.f('ix_finding_states_status'), 'finding_states', ['status'], unique=False)
    op.create_table('policy_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_version_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('engine_name', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('evaluation_duration_ms', sa.Integer(), nullable=True),
    sa.Column('fact_snapshot_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['policy_version_id'], ['policy_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_evaluations_finding_id'), 'policy_evaluations', ['finding_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_policy_version_id'), 'policy_evaluations', ['policy_version_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_resource_id'), 'policy_evaluations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_status'), 'policy_evaluations', ['status'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('fact_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['policy_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fact_id'], ['facts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_evaluation_id'), 'evidence', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_evidence_fact_id'), 'evidence', ['fact_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_fact_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_evaluation_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_policy_evaluations_status'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_resource_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_policy_version_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_finding_id'), table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_index(op.f('ix_finding_states_status'), table_name='finding_states')
    op.drop_index(op.f('ix_finding_states_finding_id'), table_name='finding_states')
    op.drop_table('finding_states')
    op.drop_index(op.f('ix_policy_versions_policy_id'), table_name='policy_versions')
    op.drop_table('policy_versions')
    op.drop_index(op.f('ix_policy_assignments_resource_id'), table_name='policy_assignments')
    op.drop_index(op.f('ix_policy_assignments_policy_id'), table_name='policy_assignments')
    op.drop_table('policy_assignments')
    op.drop_index(op.f('ix_findings_tenant_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_resource_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_origin_engine'), table_name='findings')
    op.drop_table('findings')
    op.drop_index(op.f('ix_policies_tenant_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_name'), table_name='policies')
    op.drop_table('policies')
    # ### end Alembic commands ###
