"""phase_6_organization_management

Revision ID: 35de3b6910d0
Revises: 6c8ced684665
Create Date: 2026-07-22 13:10:30.698834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35de3b6910d0'
down_revision: Union[str, Sequence[str], None] = '6c8ced684665'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_invitations',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'expired', 'cancelled', 'revoked', name='invitationstatus'), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invitation_org_status', 'organization_invitations', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_organization_invitations_email'), 'organization_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_organization_invitations_id'), 'organization_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_organization_id'), 'organization_invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_tenant_id'), 'organization_invitations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_organization_invitations_token_hash'), 'organization_invitations', ['token_hash'], unique=True)
    op.create_index('uq_active_invite', 'organization_invitations', ['organization_id', 'email'], unique=True, postgresql_where="status = 'pending'")
    op.add_column('organizations', sa.Column('description', sa.String(), nullable=True))
    
    org_status = postgresql.ENUM('active', 'pending', 'suspended', 'archived', name='organizationstatus')
    org_status.create(op.get_bind())
    
    site_status = postgresql.ENUM('active', 'maintenance', 'offline', 'archived', name='sitestatus')
    site_status.create(op.get_bind())
    
    op.add_column('organizations', sa.Column('status', sa.Enum('active', 'pending', 'suspended', 'archived', name='organizationstatus'), nullable=False))
    op.add_column('organizations', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('organizations', sa.Column('delete_reason', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('deleted_from_ip', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('deleted_from_request_id', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('organizations', sa.Column('restored_by', sa.UUID(), nullable=True))
    op.add_column('organizations', sa.Column('restore_reason', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('organizations', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('organizations', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=False)
    op.create_index('ix_org_tenant_status_deleted', 'organizations', ['tenant_id', 'status', 'deleted_at'], unique=False)
    op.create_unique_constraint('uq_org_tenant_name', 'organizations', ['tenant_id', 'name'])
    op.create_unique_constraint('uq_org_tenant_slug', 'organizations', ['tenant_id', 'slug'])
    op.create_foreign_key(None, 'organizations', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'organizations', 'users', ['restored_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'organizations', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'organizations', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('sites', sa.Column('description', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('status', sa.Enum('active', 'maintenance', 'archived', 'decommissioned', name='sitestatus'), nullable=False))
    op.add_column('sites', sa.Column('deleted_by', sa.UUID(), nullable=True))
    op.add_column('sites', sa.Column('delete_reason', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('deleted_from_ip', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('deleted_from_request_id', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('restored_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sites', sa.Column('restored_by', sa.UUID(), nullable=True))
    op.add_column('sites', sa.Column('restore_reason', sa.String(), nullable=True))
    op.add_column('sites', sa.Column('created_by', sa.UUID(), nullable=True))
    op.add_column('sites', sa.Column('updated_by', sa.UUID(), nullable=True))
    op.alter_column('sites', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('ix_sites_code'), table_name='sites')
    op.create_index(op.f('ix_sites_code'), 'sites', ['code'], unique=False)
    op.create_index('ix_site_org_status_deleted', 'sites', ['organization_id', 'status', 'deleted_at'], unique=False)
    op.create_unique_constraint('uq_site_org_code', 'sites', ['organization_id', 'code'])
    op.create_unique_constraint('uq_site_org_name', 'sites', ['organization_id', 'name'])
    op.create_foreign_key(None, 'sites', 'users', ['restored_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sites', 'users', ['deleted_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sites', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'sites', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('user_role_assignments', sa.Column('tenant_id', sa.UUID(), nullable=True))
    op.add_column('user_role_assignments', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('user_role_assignments', sa.Column('site_id', sa.UUID(), nullable=True))
    op.add_column('user_role_assignments', sa.Column('device_group_id', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_user_role_assignments_scope_id'), table_name='user_role_assignments')
    op.create_index(op.f('ix_user_role_assignments_device_group_id'), 'user_role_assignments', ['device_group_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_organization_id'), 'user_role_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_site_id'), 'user_role_assignments', ['site_id'], unique=False)
    op.create_index(op.f('ix_user_role_assignments_tenant_id'), 'user_role_assignments', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'user_role_assignments', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role_assignments', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_role_assignments', 'sites', ['site_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_role_assignments', 'scope_id')
    op.drop_column('user_role_assignments', 'scope')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role_assignments', sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_role_assignments', sa.Column('scope_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_role_assignments', type_='foreignkey')
    op.drop_constraint(None, 'user_role_assignments', type_='foreignkey')
    op.drop_constraint(None, 'user_role_assignments', type_='foreignkey')
    op.drop_index(op.f('ix_user_role_assignments_tenant_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_site_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_organization_id'), table_name='user_role_assignments')
    op.drop_index(op.f('ix_user_role_assignments_device_group_id'), table_name='user_role_assignments')
    op.create_index(op.f('ix_user_role_assignments_scope_id'), 'user_role_assignments', ['scope_id'], unique=False)
    op.drop_column('user_role_assignments', 'device_group_id')
    op.drop_column('user_role_assignments', 'site_id')
    op.drop_column('user_role_assignments', 'organization_id')
    op.drop_column('user_role_assignments', 'tenant_id')
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_constraint(None, 'sites', type_='foreignkey')
    op.drop_constraint('uq_site_org_name', 'sites', type_='unique')
    op.drop_constraint('uq_site_org_code', 'sites', type_='unique')
    op.drop_index('ix_site_org_status_deleted', table_name='sites')
    op.drop_index(op.f('ix_sites_code'), table_name='sites')
    op.create_index(op.f('ix_sites_code'), 'sites', ['code'], unique=True)
    op.alter_column('sites', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('sites', 'updated_by')
    op.drop_column('sites', 'created_by')
    op.drop_column('sites', 'restore_reason')
    op.drop_column('sites', 'restored_by')
    op.drop_column('sites', 'restored_at')
    op.drop_column('sites', 'deleted_from_request_id')
    op.drop_column('sites', 'deleted_from_ip')
    op.drop_column('sites', 'delete_reason')
    op.drop_column('sites', 'deleted_by')
    op.drop_column('sites', 'status')
    op.drop_column('sites', 'description')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_constraint(None, 'organizations', type_='foreignkey')
    op.drop_constraint('uq_org_tenant_slug', 'organizations', type_='unique')
    op.drop_constraint('uq_org_tenant_name', 'organizations', type_='unique')
    op.drop_index('ix_org_tenant_status_deleted', table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.alter_column('organizations', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('organizations', 'updated_by')
    op.drop_column('organizations', 'created_by')
    op.drop_column('organizations', 'restore_reason')
    op.drop_column('organizations', 'restored_by')
    op.drop_column('organizations', 'restored_at')
    op.drop_column('organizations', 'deleted_from_request_id')
    op.drop_column('organizations', 'deleted_from_ip')
    op.drop_column('organizations', 'delete_reason')
    op.drop_column('organizations', 'deleted_by')
    op.drop_column('organizations', 'status')
    op.drop_column('organizations', 'description')
    op.drop_index('uq_active_invite', table_name='organization_invitations', postgresql_where="status = 'pending'")
    op.drop_index(op.f('ix_organization_invitations_token_hash'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_tenant_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_organization_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_id'), table_name='organization_invitations')
    op.drop_index(op.f('ix_organization_invitations_email'), table_name='organization_invitations')
    op.drop_index('ix_invitation_org_status', table_name='organization_invitations')
    op.drop_table('organization_invitations')
    # ### end Alembic commands ###
