"""phase_7_device_domain

Revision ID: 7c63ad8a3ae7
Revises: 35de3b6910d0
Create Date: 2026-07-22 13:21:08.411608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7c63ad8a3ae7'
down_revision: Union[str, Sequence[str], None] = '35de3b6910d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_definitions',
    sa.Column('metric_key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('is_counter', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_definitions_id'), 'metric_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_metric_definitions_metric_key'), 'metric_definitions', ['metric_key'], unique=True)
    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('aggregate', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_aggregate'), 'outbox_events', ['aggregate'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_outbox_events_tenant_id'), 'outbox_events', ['tenant_id'], unique=False)
    op.create_index('ix_outbox_events_unpublished', 'outbox_events', ['occurred_at'], unique=False, postgresql_where='published_at IS NULL')
    op.create_table('credential_profiles',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('protocol', sa.String(), nullable=False),
    sa.Column('vault_reference', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_credential_profile_tenant_name')
    )
    op.create_index(op.f('ix_credential_profiles_id'), 'credential_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_credential_profiles_name'), 'credential_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_credential_profiles_tenant_id'), 'credential_profiles', ['tenant_id'], unique=False)
    op.create_table('polling_profiles',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('enabled_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_polling_profile_tenant_name')
    )
    op.create_index(op.f('ix_polling_profiles_id'), 'polling_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_polling_profiles_name'), 'polling_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_polling_profiles_tenant_id'), 'polling_profiles', ['tenant_id'], unique=False)
    op.create_table('snmp_profiles',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('timeout_ms', sa.Integer(), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_snmp_profile_tenant_name')
    )
    op.create_index(op.f('ix_snmp_profiles_id'), 'snmp_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_snmp_profiles_name'), 'snmp_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_snmp_profiles_tenant_id'), 'snmp_profiles', ['tenant_id'], unique=False)
    op.create_table('collectors',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('active', 'offline', name='collectorstatus'), nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('capacity_percent', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name', name='uq_collector_site_name')
    )
    op.create_index(op.f('ix_collectors_id'), 'collectors', ['id'], unique=False)
    op.create_index('ix_collectors_last_heartbeat', 'collectors', ['last_heartbeat'], unique=False)
    op.create_index(op.f('ix_collectors_name'), 'collectors', ['name'], unique=False)
    op.create_index(op.f('ix_collectors_site_id'), 'collectors', ['site_id'], unique=False)
    op.create_index(op.f('ix_collectors_tenant_id'), 'collectors', ['tenant_id'], unique=False)
    op.create_table('device_groups',
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name', name='uq_device_group_site_name')
    )
    op.create_index(op.f('ix_device_groups_id'), 'device_groups', ['id'], unique=False)
    op.create_index(op.f('ix_device_groups_name'), 'device_groups', ['name'], unique=False)
    op.create_index(op.f('ix_device_groups_site_id'), 'device_groups', ['site_id'], unique=False)
    op.create_table('devices',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('device_uuid', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('management_ip', postgresql.INET(), nullable=False),
    sa.Column('dns_name', sa.String(), nullable=True),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('asset_tag', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('firmware', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('supports_snmp', sa.Boolean(), nullable=False),
    sa.Column('supports_icmp', sa.Boolean(), nullable=False),
    sa.Column('supports_ssh', sa.Boolean(), nullable=False),
    sa.Column('supports_syslog', sa.Boolean(), nullable=False),
    sa.Column('supports_traps', sa.Boolean(), nullable=False),
    sa.Column('lifecycle_state', sa.Enum('provisioning', 'discovering', 'active', 'retired', 'decommissioned', name='devicelifecyclestate'), nullable=False),
    sa.Column('admin_state', sa.Enum('enabled', 'disabled', 'maintenance', name='deviceadminstate'), nullable=False),
    sa.Column('oper_state', sa.Enum('up', 'down', 'unreachable', 'unknown', name='deviceoperstate'), nullable=False),
    sa.Column('health', sa.Enum('unknown', 'good', 'warning', 'critical', name='devicehealth'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('polling_profile_id', sa.UUID(), nullable=True),
    sa.Column('snmp_profile_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['device_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['polling_profile_id'], ['polling_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snmp_profile_id'], ['snmp_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'management_ip', name='uq_device_site_ip')
    )
    op.create_index('ix_device_tenant_health', 'devices', ['tenant_id', 'health', 'deleted_at'], unique=False)
    op.create_index('ix_device_tenant_lifecycle', 'devices', ['tenant_id', 'lifecycle_state', 'deleted_at'], unique=False)
    op.create_index('ix_device_tenant_oper', 'devices', ['tenant_id', 'oper_state', 'deleted_at'], unique=False)
    op.create_index(op.f('ix_devices_device_uuid'), 'devices', ['device_uuid'], unique=True)
    op.create_index(op.f('ix_devices_group_id'), 'devices', ['group_id'], unique=False)
    op.create_index(op.f('ix_devices_hostname'), 'devices', ['hostname'], unique=False)
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)
    op.create_index(op.f('ix_devices_management_ip'), 'devices', ['management_ip'], unique=False)
    op.create_index(op.f('ix_devices_polling_profile_id'), 'devices', ['polling_profile_id'], unique=False)
    op.create_index(op.f('ix_devices_serial_number'), 'devices', ['serial_number'], unique=False)
    op.create_index(op.f('ix_devices_site_id'), 'devices', ['site_id'], unique=False)
    op.create_index(op.f('ix_devices_snmp_profile_id'), 'devices', ['snmp_profile_id'], unique=False)
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_table('device_collector_assignments',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('collector_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('primary', 'secondary', 'standby', name='collectorrole'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'collector_id', name='uq_device_collector')
    )
    op.create_index(op.f('ix_device_collector_assignments_collector_id'), 'device_collector_assignments', ['collector_id'], unique=False)
    op.create_index(op.f('ix_device_collector_assignments_device_id'), 'device_collector_assignments', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_collector_assignments_id'), 'device_collector_assignments', ['id'], unique=False)
    op.create_table('device_credential_assignments',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('credential_profile_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_profile_id'], ['credential_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'credential_profile_id', name='uq_device_cred')
    )
    op.create_index(op.f('ix_device_credential_assignments_credential_profile_id'), 'device_credential_assignments', ['credential_profile_id'], unique=False)
    op.create_index(op.f('ix_device_credential_assignments_device_id'), 'device_credential_assignments', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_credential_assignments_id'), 'device_credential_assignments', ['id'], unique=False)
    op.create_table('device_tags',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'key', name='uq_device_tag_key')
    )
    op.create_index(op.f('ix_device_tags_device_id'), 'device_tags', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_tags_id'), 'device_tags', ['id'], unique=False)
    op.create_index(op.f('ix_device_tags_key'), 'device_tags', ['key'], unique=False)
    op.create_index(op.f('ix_device_tags_value'), 'device_tags', ['value'], unique=False)
    op.create_table('interfaces',
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('if_index', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('alias', sa.String(), nullable=True),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('speed_bps', sa.Integer(), nullable=False),
    sa.Column('mac_address', postgresql.MACADDR(), nullable=True),
    sa.Column('admin_state', sa.Enum('up', 'down', 'testing', name='interfaceadminstate'), nullable=False),
    sa.Column('oper_state', sa.Enum('up', 'down', 'testing', 'unknown', 'dormant', 'not_present', 'lower_layer_down', name='interfaceoperstate'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'if_index', name='uq_interface_device_index'),
    sa.UniqueConstraint('device_id', 'name', name='uq_interface_device_name')
    )
    op.create_index('ix_interface_device_oper', 'interfaces', ['device_id', 'oper_state'], unique=False)
    op.create_index(op.f('ix_interfaces_device_id'), 'interfaces', ['device_id'], unique=False)
    op.create_index(op.f('ix_interfaces_id'), 'interfaces', ['id'], unique=False)
    op.create_index(op.f('ix_interfaces_name'), 'interfaces', ['name'], unique=False)
    op.create_table('metric_series',
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('interface_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interface_id'], ['interfaces.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['metric_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_series_device_id'), 'metric_series', ['device_id'], unique=False)
    op.create_index(op.f('ix_metric_series_id'), 'metric_series', ['id'], unique=False)
    op.create_index(op.f('ix_metric_series_interface_id'), 'metric_series', ['interface_id'], unique=False)
    op.create_index(op.f('ix_metric_series_metric_id'), 'metric_series', ['metric_id'], unique=False)
    op.create_index('uq_metric_series_target', 'metric_series', ['device_id', 'metric_id', 'interface_id'], unique=True, postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_metric_series_target', table_name='metric_series', postgresql_nulls_not_distinct=True)
    op.drop_index(op.f('ix_metric_series_metric_id'), table_name='metric_series')
    op.drop_index(op.f('ix_metric_series_interface_id'), table_name='metric_series')
    op.drop_index(op.f('ix_metric_series_id'), table_name='metric_series')
    op.drop_index(op.f('ix_metric_series_device_id'), table_name='metric_series')
    op.drop_table('metric_series')
    op.drop_index(op.f('ix_interfaces_name'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_id'), table_name='interfaces')
    op.drop_index(op.f('ix_interfaces_device_id'), table_name='interfaces')
    op.drop_index('ix_interface_device_oper', table_name='interfaces')
    op.drop_table('interfaces')
    op.drop_index(op.f('ix_device_tags_value'), table_name='device_tags')
    op.drop_index(op.f('ix_device_tags_key'), table_name='device_tags')
    op.drop_index(op.f('ix_device_tags_id'), table_name='device_tags')
    op.drop_index(op.f('ix_device_tags_device_id'), table_name='device_tags')
    op.drop_table('device_tags')
    op.drop_index(op.f('ix_device_credential_assignments_id'), table_name='device_credential_assignments')
    op.drop_index(op.f('ix_device_credential_assignments_device_id'), table_name='device_credential_assignments')
    op.drop_index(op.f('ix_device_credential_assignments_credential_profile_id'), table_name='device_credential_assignments')
    op.drop_table('device_credential_assignments')
    op.drop_index(op.f('ix_device_collector_assignments_id'), table_name='device_collector_assignments')
    op.drop_index(op.f('ix_device_collector_assignments_device_id'), table_name='device_collector_assignments')
    op.drop_index(op.f('ix_device_collector_assignments_collector_id'), table_name='device_collector_assignments')
    op.drop_table('device_collector_assignments')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_snmp_profile_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_site_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_serial_number'), table_name='devices')
    op.drop_index(op.f('ix_devices_polling_profile_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_management_ip'), table_name='devices')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_hostname'), table_name='devices')
    op.drop_index(op.f('ix_devices_group_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_uuid'), table_name='devices')
    op.drop_index('ix_device_tenant_oper', table_name='devices')
    op.drop_index('ix_device_tenant_lifecycle', table_name='devices')
    op.drop_index('ix_device_tenant_health', table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_device_groups_site_id'), table_name='device_groups')
    op.drop_index(op.f('ix_device_groups_name'), table_name='device_groups')
    op.drop_index(op.f('ix_device_groups_id'), table_name='device_groups')
    op.drop_table('device_groups')
    op.drop_index(op.f('ix_collectors_tenant_id'), table_name='collectors')
    op.drop_index(op.f('ix_collectors_site_id'), table_name='collectors')
    op.drop_index(op.f('ix_collectors_name'), table_name='collectors')
    op.drop_index('ix_collectors_last_heartbeat', table_name='collectors')
    op.drop_index(op.f('ix_collectors_id'), table_name='collectors')
    op.drop_table('collectors')
    op.drop_index(op.f('ix_snmp_profiles_tenant_id'), table_name='snmp_profiles')
    op.drop_index(op.f('ix_snmp_profiles_name'), table_name='snmp_profiles')
    op.drop_index(op.f('ix_snmp_profiles_id'), table_name='snmp_profiles')
    op.drop_table('snmp_profiles')
    op.drop_index(op.f('ix_polling_profiles_tenant_id'), table_name='polling_profiles')
    op.drop_index(op.f('ix_polling_profiles_name'), table_name='polling_profiles')
    op.drop_index(op.f('ix_polling_profiles_id'), table_name='polling_profiles')
    op.drop_table('polling_profiles')
    op.drop_index(op.f('ix_credential_profiles_tenant_id'), table_name='credential_profiles')
    op.drop_index(op.f('ix_credential_profiles_name'), table_name='credential_profiles')
    op.drop_index(op.f('ix_credential_profiles_id'), table_name='credential_profiles')
    op.drop_table('credential_profiles')
    op.drop_index('ix_outbox_events_unpublished', table_name='outbox_events', postgresql_where='published_at IS NULL')
    op.drop_index(op.f('ix_outbox_events_tenant_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_metric_definitions_metric_key'), table_name='metric_definitions')
    op.drop_index(op.f('ix_metric_definitions_id'), table_name='metric_definitions')
    op.drop_table('metric_definitions')
    # ### end Alembic commands ###
