"""refine_collector_and_keys

Revision ID: 904b53a5698f
Revises: 7c63ad8a3ae7
Create Date: 2026-07-25 13:11:18.903366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '904b53a5698f'
down_revision: Union[str, Sequence[str], None] = '7c63ad8a3ae7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_registration_keys',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('max_registrations', sa.Integer(), nullable=False),
    sa.Column('used_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_registration_keys_id'), 'collector_registration_keys', ['id'], unique=False)
    op.create_index(op.f('ix_collector_registration_keys_key_hash'), 'collector_registration_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_collector_registration_keys_site_id'), 'collector_registration_keys', ['site_id'], unique=False)
    op.create_index(op.f('ix_collector_registration_keys_tenant_id'), 'collector_registration_keys', ['tenant_id'], unique=False)
    op.add_column('collectors', sa.Column('machine_id', sa.String(), nullable=False))
    op.add_column('collectors', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('collectors', sa.Column('python_version', sa.String(), nullable=True))
    op.add_column('collectors', sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.create_index(op.f('ix_collectors_machine_id'), 'collectors', ['machine_id'], unique=True)
    op.drop_column('collectors', 'status')
    op.drop_constraint(op.f('uq_device_site_ip'), 'devices', type_='unique')
    op.create_index('uq_active_device_site_ip', 'devices', ['site_id', 'management_ip'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_device_site_ip', table_name='devices', postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_unique_constraint(op.f('uq_device_site_ip'), 'devices', ['site_id', 'management_ip'], postgresql_nulls_not_distinct=False)
    op.add_column('collectors', sa.Column('status', postgresql.ENUM('active', 'offline', name='collectorstatus'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_collectors_machine_id'), table_name='collectors')
    op.drop_column('collectors', 'capabilities')
    op.drop_column('collectors', 'python_version')
    op.drop_column('collectors', 'platform')
    op.drop_column('collectors', 'machine_id')
    op.drop_index(op.f('ix_collector_registration_keys_tenant_id'), table_name='collector_registration_keys')
    op.drop_index(op.f('ix_collector_registration_keys_site_id'), table_name='collector_registration_keys')
    op.drop_index(op.f('ix_collector_registration_keys_key_hash'), table_name='collector_registration_keys')
    op.drop_index(op.f('ix_collector_registration_keys_id'), table_name='collector_registration_keys')
    op.drop_table('collector_registration_keys')
    # ### end Alembic commands ###
