"""Add CollectorJob and CollectorEvent

Revision ID: ad5efdc3c9be
Revises: 904b53a5698f
Create Date: 2026-07-25 13:34:40.770007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad5efdc3c9be'
down_revision: Union[str, Sequence[str], None] = '904b53a5698f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('collector_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('REGISTERED', 'HEARTBEAT', 'HEARTBEAT_MISSED', 'OFFLINE', 'ONLINE', 'TOKEN_REFRESH', 'JOB_LEASED', 'JOB_STARTED', 'JOB_COMPLETED', 'JOB_FAILED', name='collectoreventtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correlation_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_events_collector_id'), 'collector_events', ['collector_id'], unique=False)
    op.create_index(op.f('ix_collector_events_correlation_id'), 'collector_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_collector_events_event_type'), 'collector_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_collector_events_id'), 'collector_events', ['id'], unique=False)
    op.create_index(op.f('ix_collector_events_tenant_id'), 'collector_events', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_collector_events_timestamp'), 'collector_events', ['timestamp'], unique=False)
    op.create_table('collector_jobs',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('assigned_collector_id', sa.UUID(), nullable=True),
    sa.Column('leased_by', sa.String(), nullable=True),
    sa.Column('lease_token', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('ICMP_PING', 'SNMP_POLL', 'DISCOVERY', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'LEASED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_collector_id'], ['collectors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collector_jobs_assigned_collector_id'), 'collector_jobs', ['assigned_collector_id'], unique=False)
    op.create_index(op.f('ix_collector_jobs_id'), 'collector_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_collector_jobs_lease_expires_at'), 'collector_jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_collector_jobs_lease_token'), 'collector_jobs', ['lease_token'], unique=False)
    op.create_index(op.f('ix_collector_jobs_priority'), 'collector_jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_collector_jobs_scheduled_at'), 'collector_jobs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_collector_jobs_site_id'), 'collector_jobs', ['site_id'], unique=False)
    op.create_index(op.f('ix_collector_jobs_status'), 'collector_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_collector_jobs_tenant_id'), 'collector_jobs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_collector_jobs_type'), 'collector_jobs', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collector_jobs_type'), table_name='collector_jobs')
    op.drop_index(op.f('ix_collector_jobs_tenant_id'), table_name='collector_jobs')
    op.drop_index(op.f('ix_collector_jobs_status'), table_name='collector_jobs')
    op.drop_index(op.f('ix_collector_jobs_site_id'), table_name='collector_jobs')
    op.drop_index(op.f('ix_collector_jobs_scheduled_at'), table_name='collector_jobs')
    op.drop_index(op.f('ix_collector_jobs_priority'), table_name='collector_jobs')
    op.drop_index(op.f('ix_collector_jobs_lease_token'), table_name='collector_jobs')
    op.drop_index(op.f('ix_collector_jobs_lease_expires_at'), table_name='collector_jobs')
    op.drop_index(op.f('ix_collector_jobs_id'), table_name='collector_jobs')
    op.drop_index(op.f('ix_collector_jobs_assigned_collector_id'), table_name='collector_jobs')
    op.drop_table('collector_jobs')
    op.drop_index(op.f('ix_collector_events_timestamp'), table_name='collector_events')
    op.drop_index(op.f('ix_collector_events_tenant_id'), table_name='collector_events')
    op.drop_index(op.f('ix_collector_events_id'), table_name='collector_events')
    op.drop_index(op.f('ix_collector_events_event_type'), table_name='collector_events')
    op.drop_index(op.f('ix_collector_events_correlation_id'), table_name='collector_events')
    op.drop_index(op.f('ix_collector_events_collector_id'), table_name='collector_events')
    op.drop_table('collector_events')
    # ### end Alembic commands ###
