"""Add rich metadata to Resource

Revision ID: c60c6debb44d
Revises: e8ce7f53b132
Create Date: 2026-08-05 15:55:41.479500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c60c6debb44d'
down_revision: Union[str, Sequence[str], None] = 'e8ce7f53b132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('importance', sa.Integer(), nullable=True))
    op.add_column('resources', sa.Column('business_service', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('sla_tier', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('owner_team', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('environment', sa.String(), nullable=True))
    op.add_column('resources', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_resources_business_service'), 'resources', ['business_service'], unique=False)
    op.create_index(op.f('ix_resources_environment'), 'resources', ['environment'], unique=False)
    op.create_index(op.f('ix_resources_owner_team'), 'resources', ['owner_team'], unique=False)
    op.create_index(op.f('ix_resources_sla_tier'), 'resources', ['sla_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_sla_tier'), table_name='resources')
    op.drop_index(op.f('ix_resources_owner_team'), table_name='resources')
    op.drop_index(op.f('ix_resources_environment'), table_name='resources')
    op.drop_index(op.f('ix_resources_business_service'), table_name='resources')
    op.drop_column('resources', 'tags')
    op.drop_column('resources', 'environment')
    op.drop_column('resources', 'owner_team')
    op.drop_column('resources', 'sla_tier')
    op.drop_column('resources', 'business_service')
    op.drop_column('resources', 'importance')
    # ### end Alembic commands ###
