"""Add Incident and PlatformEvent models

Revision ID: cc34c9084465
Revises: c60c6debb44d
Create Date: 2026-08-05 16:27:44.931401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc34c9084465'
down_revision: Union[str, Sequence[str], None] = 'c60c6debb44d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('aggregate_type', sa.String(), nullable=False),
    sa.Column('aggregate_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('causation_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_events_aggregate_id'), 'platform_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_platform_events_aggregate_type'), 'platform_events', ['aggregate_type'], unique=False)
    op.create_index(op.f('ix_platform_events_causation_id'), 'platform_events', ['causation_id'], unique=False)
    op.create_index(op.f('ix_platform_events_correlation_id'), 'platform_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_platform_events_event_type'), 'platform_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_platform_events_occurred_at'), 'platform_events', ['occurred_at'], unique=False)
    op.create_index('ix_platform_events_type_time', 'platform_events', ['event_type', 'occurred_at'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('blast_radius', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('root_cause_resource_id', sa.UUID(), nullable=True),
    sa.Column('affected_business_services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeline_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['root_cause_resource_id'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_priority'), 'incidents', ['priority'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index('ix_incidents_status_severity', 'incidents', ['status', 'severity'], unique=False)
    op.create_table('incident_findings',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('finding_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'finding_id')
    )
    op.create_table('incident_resources',
    sa.Column('incident_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'resource_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_resources')
    op.drop_table('incident_findings')
    op.drop_index('ix_incidents_status_severity', table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_priority'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_platform_events_type_time', table_name='platform_events')
    op.drop_index(op.f('ix_platform_events_occurred_at'), table_name='platform_events')
    op.drop_index(op.f('ix_platform_events_event_type'), table_name='platform_events')
    op.drop_index(op.f('ix_platform_events_correlation_id'), table_name='platform_events')
    op.drop_index(op.f('ix_platform_events_causation_id'), table_name='platform_events')
    op.drop_index(op.f('ix_platform_events_aggregate_type'), table_name='platform_events')
    op.drop_index(op.f('ix_platform_events_aggregate_id'), table_name='platform_events')
    op.drop_table('platform_events')
    # ### end Alembic commands ###
