"""Add engine column to policy version, metadata to evaluation

Revision ID: e8ce7f53b132
Revises: f4a646a4e1f2
Create Date: 2026-08-05 15:10:40.322761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e8ce7f53b132'
down_revision: Union[str, Sequence[str], None] = 'f4a646a4e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_evaluations', sa.Column('trigger', sa.String(), server_default='API', nullable=False))
    op.add_column('policy_evaluations', sa.Column('started_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('policy_evaluations', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('policy_evaluations', 'evaluated_at')
    op.add_column('policy_versions', sa.Column('engine', sa.String(), server_default='configuration', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_versions', 'engine')
    op.add_column('policy_evaluations', sa.Column('evaluated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_column('policy_evaluations', 'finished_at')
    op.drop_column('policy_evaluations', 'started_at')
    op.drop_column('policy_evaluations', 'trigger')
    # ### end Alembic commands ###
