"""Add trace column

Revision ID: f4a646a4e1f2
Revises: 15ad077c1d98
Create Date: 2026-08-05 13:45:16.953955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4a646a4e1f2'
down_revision: Union[str, Sequence[str], None] = '15ad077c1d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy_evaluations', sa.Column('trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('policy_evaluations', 'trace')
    # ### end Alembic commands ###
