from abc import ABC, abstractmethod
from typing import List
from app.services.ai.schemas import AIRequest, AIResponse

class AIProvider(ABC):
    @property
    @abstractmethod
    def capabilities(self) -> List[str]:
        """e.g. ['structured_output', 'json_mode', 'vision']"""
        pass
        
    @abstractmethod
    def execute(self, request: AIRequest, rendered_prompt: str, system_prompt: str) -> AIResponse:
        pass

class MockAIProvider(AIProvider):
    @property
    def capabilities(self) -> List[str]:
        return ["structured_output"]
        
    def execute(self, request: AIRequest, rendered_prompt: str, system_prompt: str) -> AIResponse:
        from app.services.ai.schemas import Citation
        
        # In a real provider, we'd parse the LLM JSON output.
        # Here we mock it.
        return AIResponse(
            content="This is a mocked AI response generated by the MockAIProvider.",
            citations=[
                Citation(
                    type="Incident",
                    id=str(request.knowledge.incident.get("id")) if request.knowledge.incident else "unknown",
                    title="Source Incident",
                    confidence=0.99
                )
            ],
            assumptions=["Assuming mock data is correct."],
            confidence=0.95,
            usage={"prompt_tokens": 100, "completion_tokens": 50},
            latency_ms=150,
            provider="mock",
            model="mock-v1",
            prompt_version="1.0"
        )
